spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    showSql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 31427926172-tp0s1rpd3d00jdembeds0frq1lkmbvr9.apps.googleusercontent.com
            client-secret: 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
